# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('count', models.PositiveIntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
