# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_auto_20160904_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Max Amount ($)'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='count',
            field=models.PositiveIntegerField(null=True, verbose_name='Number of Awards (leave blank if unknown)'),
        ),
    ]
