# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20160905_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Max Amount ($)'),
        ),
    ]
