# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_auto_20160912_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Awards (leave blank if unknown)'),
        ),
    ]
