# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20160912_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='count',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='verified',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='status',
            field=models.IntegerField(choices=[(0, 'ARCHIVED'), (1, 'UNVERIFIED'), (2, 'VERIFIED')], default=1, help_text='The status of the scholarship: verified, unverified, archived'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=scholarships.models.ScholarshipAmountField(default=0, help_text='Either the max reward amount, FULL_TUITION, or UNKNOWN', verbose_name='Scholarship Amount ($)'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date a scholarship was added to the database'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='The date a scholarship was last updated'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(help_text='Deadline of a scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, help_text='Scholarship description provided'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL of the scholarship details'),
        ),
    ]
